global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.122.34:9093
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.122.34:9090
- job_name: 'my_docker_metrics'
  static_configs:
    - targets:
      - 192.168.122.34:9417
- job_name: node1
  static_configs:
  - targets:
    - 192.168.122.34:9100
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.122.34:8081
- job_name: 'blackbox_tcp'
  metrics_path: /probe
  params:
    module: [tcp_connect]
  static_configs:
    - targets:
      - 192.168.122.34:80
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.122.34:9115
